// src/utils/elements.ts

export interface ElementVisualData {
  color: string;
  textColor: string;
  radiusScale: number;
}

// Cores baseadas no padrão Jmol/CPK e escalas baseadas em raios atômicos relativos.
export const ELEMENT_DATA: Record<string, ElementVisualData> = {
  H: { color: "#FFFFFF", textColor: "#333", radiusScale: 0.53 },
  He: { color: "#D9FFFF", textColor: "#333", radiusScale: 0.31 },
  Li: { color: "#CC80FF", textColor: "#FFF", radiusScale: 1.67 },
  Be: { color: "#C2FF00", textColor: "#333", radiusScale: 1.12 },
  B: { color: "#FFB5B5", textColor: "#333", radiusScale: 0.87 },
  C: { color: "#333333", textColor: "#FFF", radiusScale: 0.67 },
  N: { color: "#3050F8", textColor: "#FFF", radiusScale: 0.56 },
  O: { color: "#FF0D0D", textColor: "#FFF", radiusScale: 0.48 },
  F: { color: "#90E050", textColor: "#333", radiusScale: 0.42 },
  Ne: { color: "#B3E3F5", textColor: "#333", radiusScale: 0.38 },
  Na: { color: "#AB5CF2", textColor: "#FFF", radiusScale: 1.9 },
  Mg: { color: "#8AFF00", textColor: "#333", radiusScale: 1.45 },
  Al: { color: "#BFA6A6", textColor: "#FFF", radiusScale: 1.18 },
  Si: { color: "#F0C8A0", textColor: "#333", radiusScale: 1.11 },
  P: { color: "#FF8000", textColor: "#FFF", radiusScale: 0.98 },
  S: { color: "#FFFF30", textColor: "#333", radiusScale: 0.88 },
  Cl: { color: "#1FF01F", textColor: "#333", radiusScale: 0.79 },
  Ar: { color: "#80D1E3", textColor: "#333", radiusScale: 0.71 },
  K: { color: "#8F40D4", textColor: "#FFF", radiusScale: 2.43 },
  Ca: { color: "#3DFF00", textColor: "#333", radiusScale: 1.94 },
  Sc: { color: "#E6E6E6", textColor: "#333", radiusScale: 1.84 },
  Ti: { color: "#BFC2C7", textColor: "#333", radiusScale: 1.76 },
  V: { color: "#A6A6AB", textColor: "#FFF", radiusScale: 1.71 },
  Cr: { color: "#8A99C7", textColor: "#FFF", radiusScale: 1.66 },
  Mn: { color: "#9C7AC7", textColor: "#FFF", radiusScale: 1.61 },
  Fe: { color: "#E06633", textColor: "#FFF", radiusScale: 1.56 },
  Co: { color: "#F090A0", textColor: "#333", radiusScale: 1.52 },
  Ni: { color: "#50D050", textColor: "#FFF", radiusScale: 1.49 },
  Cu: { color: "#C88033", textColor: "#FFF", radiusScale: 1.45 },
  Zn: { color: "#7D80B0", textColor: "#FFF", radiusScale: 1.42 },
  Ga: { color: "#C28F8F", textColor: "#FFF", radiusScale: 1.36 },
  Ge: { color: "#668F8F", textColor: "#FFF", radiusScale: 1.25 },
  As: { color: "#BD80E3", textColor: "#FFF", radiusScale: 1.14 },
  Se: { color: "#FFA100", textColor: "#333", radiusScale: 1.03 },
  Br: { color: "#A62929", textColor: "#FFF", radiusScale: 0.94 },
  Kr: { color: "#5CB8D1", textColor: "#333", radiusScale: 0.88 },
  Rb: { color: "#702EB0", textColor: "#FFF", radiusScale: 2.65 },
  Sr: { color: "#00FF00", textColor: "#333", radiusScale: 2.19 },
  Y: { color: "#94FFFF", textColor: "#333", radiusScale: 2.12 },
  Zr: { color: "#94E0E0", textColor: "#333", radiusScale: 2.06 },
  Nb: { color: "#73C2C9", textColor: "#333", radiusScale: 1.98 },
  Mo: { color: "#54B5B5", textColor: "#FFF", radiusScale: 1.9 },
  Tc: { color: "#3B9E9E", textColor: "#FFF", radiusScale: 1.83 },
  Ru: { color: "#248F8F", textColor: "#FFF", radiusScale: 1.78 },
  Rh: { color: "#0A7D8C", textColor: "#FFF", radiusScale: 1.73 },
  Pd: { color: "#006985", textColor: "#FFF", radiusScale: 1.69 },
  Ag: { color: "#C0C0C0", textColor: "#333", radiusScale: 1.65 },
  Cd: { color: "#FFD98F", textColor: "#333", radiusScale: 1.61 },
  In: { color: "#A67573", textColor: "#FFF", radiusScale: 1.56 },
  Sn: { color: "#668080", textColor: "#FFF", radiusScale: 1.45 },
  Sb: { color: "#9E63B5", textColor: "#FFF", radiusScale: 1.33 },
  Te: { color: "#D47A00", textColor: "#FFF", radiusScale: 1.23 },
  I: { color: "#940094", textColor: "#FFF", radiusScale: 1.15 },
  Xe: { color: "#429EB0", textColor: "#FFF", radiusScale: 1.08 },
  Cs: { color: "#57178F", textColor: "#FFF", radiusScale: 2.98 },
  Ba: { color: "#00C900", textColor: "#FFF", radiusScale: 2.53 },
  La: { color: "#70D4FF", textColor: "#333", radiusScale: 2.26 },
  Ce: { color: "#FFFFC7", textColor: "#333", radiusScale: 2.1 },
  Pr: { color: "#D9FFC7", textColor: "#333", radiusScale: 2.03 },
  Nd: { color: "#C7FFC7", textColor: "#333", radiusScale: 1.99 },
  Pm: { color: "#A3FFC7", textColor: "#333", radiusScale: 1.97 },
  Sm: { color: "#8FFFC7", textColor: "#333", radiusScale: 1.94 },
  Eu: { color: "#61FFC7", textColor: "#333", radiusScale: 1.92 },
  Gd: { color: "#45FFC7", textColor: "#333", radiusScale: 1.89 },
  Tb: { color: "#30FFC7", textColor: "#333", radiusScale: 1.86 },
  Dy: { color: "#1FFFC7", textColor: "#333", radiusScale: 1.84 },
  Ho: { color: "#00FF9C", textColor: "#333", radiusScale: 1.82 },
  Er: { color: "#00E673", textColor: "#333", radiusScale: 1.81 },
  Tm: { color: "#00D452", textColor: "#FFF", radiusScale: 1.79 },
  Yb: { color: "#00BF38", textColor: "#FFF", radiusScale: 1.76 },
  Lu: { color: "#00AB24", textColor: "#FFF", radiusScale: 1.75 },
  Hf: { color: "#4DC2FF", textColor: "#333", radiusScale: 1.71 },
  Ta: { color: "#4DA6FF", textColor: "#333", radiusScale: 1.66 },
  W: { color: "#2194D6", textColor: "#FFF", radiusScale: 1.62 },
  Re: { color: "#267DAB", textColor: "#FFF", radiusScale: 1.58 },
  Os: { color: "#266696", textColor: "#FFF", radiusScale: 1.54 },
  Ir: { color: "#175487", textColor: "#FFF", radiusScale: 1.51 },
  Pt: { color: "#D0D0E0", textColor: "#333", radiusScale: 1.48 },
  Au: { color: "#FFD123", textColor: "#333", radiusScale: 1.46 },
  Hg: { color: "#B8B8D0", textColor: "#333", radiusScale: 1.44 },
  Tl: { color: "#A6544D", textColor: "#FFF", radiusScale: 1.41 },
  Pb: { color: "#575961", textColor: "#FFF", radiusScale: 1.38 },
  Bi: { color: "#9E4FB5", textColor: "#FFF", radiusScale: 1.35 },
  Po: { color: "#AB5C00", textColor: "#FFF", radiusScale: 1.31 },
  At: { color: "#754F45", textColor: "#FFF", radiusScale: 1.28 },
  Rn: { color: "#428296", textColor: "#FFF", radiusScale: 1.25 },
  Fr: { color: "#420066", textColor: "#FFF", radiusScale: 3.48 },
  Ra: { color: "#007D00", textColor: "#FFF", radiusScale: 2.83 },
  Ac: { color: "#70ABFA", textColor: "#333", radiusScale: 2.47 },
  Th: { color: "#00BAFF", textColor: "#333", radiusScale: 2.37 },
  Pa: { color: "#00A1FF", textColor: "#FFF", radiusScale: 2.27 },
  U: { color: "#008FFF", textColor: "#FFF", radiusScale: 2.18 },
  Np: { color: "#0080FF", textColor: "#FFF", radiusScale: 2.1 },
  Pu: { color: "#006BFF", textColor: "#FFF", radiusScale: 2.03 },
  Am: { color: "#545CF2", textColor: "#FFF", radiusScale: 1.97 },
  Cm: { color: "#785CE3", textColor: "#FFF", radiusScale: 1.91 },
  Bk: { color: "#8A4FE3", textColor: "#FFF", radiusScale: 1.86 },
  Cf: { color: "#A136D4", textColor: "#FFF", radiusScale: 1.82 },
  Es: { color: "#B31FD4", textColor: "#FFF", radiusScale: 1.78 },
  Fm: { color: "#B31FBA", textColor: "#FFF", radiusScale: 1.74 },
  Md: { color: "#B30DA6", textColor: "#FFF", radiusScale: 1.7 },
  No: { color: "#BD0D87", textColor: "#FFF", radiusScale: 1.67 },
  Lr: { color: "#C70066", textColor: "#FFF", radiusScale: 1.64 },
  Rf: { color: "#CC0059", textColor: "#FFF", radiusScale: 1.61 },
  Db: { color: "#D1004F", textColor: "#FFF", radiusScale: 1.58 },
  Sg: { color: "#D90045", textColor: "#FFF", radiusScale: 1.55 },
  Bh: { color: "#E00038", textColor: "#FFF", radiusScale: 1.52 },
  Hs: { color: "#E6002E", textColor: "#FFF", radiusScale: 1.5 },
  Mt: { color: "#EB0026", textColor: "#FFF", radiusScale: 1.48 },
  Ds: { color: "#F0001F", textColor: "#FFF", radiusScale: 1.46 },
  Rg: { color: "#F50014", textColor: "#FFF", radiusScale: 1.44 },
  Cn: { color: "#FA000A", textColor: "#FFF", radiusScale: 1.42 },
  Nh: { color: "#FF0000", textColor: "#FFF", radiusScale: 1.4 },
  Fl: { color: "#FF0000", textColor: "#FFF", radiusScale: 1.38 },
  Mc: { color: "#FF0000", textColor: "#FFF", radiusScale: 1.36 },
  Lv: { color: "#FF0000", textColor: "#FFF", radiusScale: 1.35 },
  Ts: { color: "#FF0000", textColor: "#FFF", radiusScale: 1.34 },
  Og: { color: "#FF0000", textColor: "#FFF", radiusScale: 1.33 },
  DEFAULT: { color: "#95a5a6", textColor: "#FFFFFF", radiusScale: 1.0 },
};

export const ELEMENT_NAMES: Record<string, string> = {
  H: "Hidrogênio",
  He: "Hélio",
  Li: "Lítio",
  Be: "Berílio",
  B: "Boro",
  C: "Carbono",
  N: "Nitrogênio",
  O: "Oxigênio",
  F: "Flúor",
  Ne: "Neônio",
  Na: "Sódio",
  Mg: "Magnésio",
  Al: "Alumínio",
  Si: "Silício",
  P: "Fósforo",
  S: "Enxofre",
  Cl: "Cloro",
  Ar: "Argônio",
  K: "Potássio",
  Ca: "Cálcio",
  Sc: "Escândio",
  Ti: "Titânio",
  V: "Vanádio",
  Cr: "Cromo",
  Mn: "Manganês",
  Fe: "Ferro",
  Co: "Cobalto",
  Ni: "Níquel",
  Cu: "Cobre",
  Zn: "Zinco",
  Ga: "Gálio",
  Ge: "Germânio",
  As: "Arsênio",
  Se: "Selênio",
  Br: "Bromo",
  Kr: "Criptônio",
  Rb: "Rubídio",
  Sr: "Estrôncio",
  Y: "Ítrio",
  Zr: "Zircônio",
  Nb: "Nióbio",
  Mo: "Molibdênio",
  Tc: "Tecnécio",
  Ru: "Rutênio",
  Rh: "Ródio",
  Pd: "Paládio",
  Ag: "Prata",
  Cd: "Cádmio",
  In: "Índio",
  Sn: "Estanho",
  Sb: "Antimônio",
  Te: "Telúrio",
  I: "Iodo",
  Xe: "Xenônio",
  Cs: "Césio",
  Ba: "Bário",
  La: "Lantânio",
  Ce: "Cério",
  Pr: "Praseodímio",
  Nd: "Neodímio",
  Pm: "Promécio",
  Sm: "Samário",
  Eu: "Európio",
  Gd: "Gadolínio",
  Tb: "Térbio",
  Dy: "Disprósio",
  Ho: "Hólmio",
  Er: "Érbio",
  Tm: "Túlio",
  Yb: "Itérbio",
  Lu: "Lutécio",
  Hf: "Háfnio",
  Ta: "Tântalo",
  W: "Tungstênio",
  Re: "Rênio",
  Os: "Ósmio",
  Ir: "Irídio",
  Pt: "Platina",
  Au: "Ouro",
  Hg: "Mercúrio",
  Tl: "Tálio",
  Pb: "Chumbo",
  Bi: "Bismuto",
  Po: "Polônio",
  At: "Ástato",
  Rn: "Radônio",
  Fr: "Frâncio",
  Ra: "Rádio",
  Ac: "Actínio",
  Th: "Tório",
  Pa: "Protactínio",
  U: "Urânio",
  Np: "Netúnio",
  Pu: "Plutônio",
  Am: "Amerício",
  Cm: "Cúrio",
  Bk: "Berquélio",
  Cf: "Califórnio",
  Es: "Einstêinio",
  Fm: "Férmio",
  Md: "Mendelévio",
  No: "Nobélio",
  Lr: "Laurêncio",
  Rf: "Rutherfórdio",
  Db: "Dúbnio",
  Sg: "Seabórgio",
  Bh: "Bóhrio",
  Hs: "Hássio",
  Mt: "Meitnério",
  Ds: "Darmstádio",
  Rg: "Roentgênio",
  Cn: "Copernício",
  Nh: "Nihônio",
  Fl: "Fleróvio",
  Mc: "Moscóvio",
  Lv: "Livermório",
  Ts: "Tenessino",
  Og: "Oganessônio",
};
